/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ttt;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class pageOne extends javax.swing.JFrame {

    /**
     * Creates new form pageOne
     */
    public pageOne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        heading = new javax.swing.JLabel();
        boxA = new javax.swing.JPanel();
        startBack = new javax.swing.JPanel();
        startBtn = new javax.swing.JLabel();
        settingsBack = new javax.swing.JPanel();
        settingsBtn = new javax.swing.JLabel();
        helpBack = new javax.swing.JPanel();
        helpBtn = new javax.swing.JLabel();
        creditsBack = new javax.swing.JPanel();
        creditsBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TIC TAC TOE");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(550, 670));
        setSize(new java.awt.Dimension(540, 700));

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setForeground(new java.awt.Color(255, 255, 255));

        heading.setBackground(new java.awt.Color(0, 0, 0));
        heading.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("TIC TAC TOE");

        boxA.setBackground(new java.awt.Color(0, 0, 0));
        boxA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        boxA.setForeground(new java.awt.Color(255, 255, 255));
        boxA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boxA.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        startBack.setBackground(new java.awt.Color(0, 0, 0));
        startBack.setForeground(new java.awt.Color(255, 255, 255));

        startBtn.setBackground(new java.awt.Color(0, 0, 9));
        startBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        startBtn.setForeground(new java.awt.Color(255, 255, 255));
        startBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startBtn.setText("START");
        startBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout startBackLayout = new javax.swing.GroupLayout(startBack);
        startBack.setLayout(startBackLayout);
        startBackLayout.setHorizontalGroup(
            startBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        startBackLayout.setVerticalGroup(
            startBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startBackLayout.createSequentialGroup()
                .addComponent(startBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        boxA.add(startBack);

        settingsBack.setBackground(new java.awt.Color(0, 0, 0));
        settingsBack.setForeground(new java.awt.Color(255, 255, 255));

        settingsBtn.setBackground(new java.awt.Color(0, 0, 0));
        settingsBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        settingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        settingsBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsBtn.setText("SETTINGS");
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout settingsBackLayout = new javax.swing.GroupLayout(settingsBack);
        settingsBack.setLayout(settingsBackLayout);
        settingsBackLayout.setHorizontalGroup(
            settingsBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        settingsBackLayout.setVerticalGroup(
            settingsBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(settingsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        boxA.add(settingsBack);

        helpBack.setBackground(new java.awt.Color(0, 0, 0));
        helpBack.setForeground(new java.awt.Color(255, 255, 255));

        helpBtn.setBackground(new java.awt.Color(0, 0, 0));
        helpBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        helpBtn.setForeground(new java.awt.Color(255, 255, 255));
        helpBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpBtn.setText("HELP");
        helpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout helpBackLayout = new javax.swing.GroupLayout(helpBack);
        helpBack.setLayout(helpBackLayout);
        helpBackLayout.setHorizontalGroup(
            helpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(helpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        helpBackLayout.setVerticalGroup(
            helpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(helpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        boxA.add(helpBack);

        creditsBack.setBackground(new java.awt.Color(0, 0, 0));
        creditsBack.setForeground(new java.awt.Color(255, 255, 255));

        creditsBtn.setBackground(new java.awt.Color(0, 0, 0));
        creditsBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        creditsBtn.setForeground(new java.awt.Color(255, 255, 255));
        creditsBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditsBtn.setText("CREDITS");
        creditsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditsBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout creditsBackLayout = new javax.swing.GroupLayout(creditsBack);
        creditsBack.setLayout(creditsBackLayout);
        creditsBackLayout.setHorizontalGroup(
            creditsBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        creditsBackLayout.setVerticalGroup(
            creditsBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        boxA.add(creditsBack);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("- v1.0");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boxA, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72)
                .addComponent(boxA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(250, 250, 250)
                .addComponent(jLabel1))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        // TODO add your handling code here:
        close();
        new Settings().setVisible(true);
    }//GEN-LAST:event_settingsBtnMouseClicked

    private void helpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpBtnMouseClicked
        // TODO add your handling code here:
        close();
        new Help().setVisible(true);
    }//GEN-LAST:event_helpBtnMouseClicked

    private void creditsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBtnMouseClicked
        // TODO add your handling code here:
        close();
        new EndCredits().setVisible(true);
    }//GEN-LAST:event_creditsBtnMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void startBtnMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_startBtnMouseEntered
        // TODO add your handling code here:
        startBtn.setBackground(new Color(255, 255, 255));
        startBtn.setForeground(new Color(0, 0, 0));
        startBack.setBackground(new Color(255, 255, 255));
    }// GEN-LAST:event_startBtnMouseEntered

    private void startBtnMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_startBtnMouseExited
        // TODO add your handling code here:
        startBtn.setBackground(new Color(0, 0, 0));
        startBtn.setForeground(new Color(255, 255, 255));
        startBack.setBackground(new Color(0, 0, 0));
    }// GEN-LAST:event_startBtnMouseExited

    private void settingsBtnMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_settingsBtnMouseEntered
        // TODO add your handling code here:
        settingsBtn.setBackground(new Color(255, 255, 255));
        settingsBtn.setForeground(new Color(0, 0, 0));
        settingsBack.setBackground(new Color(255, 255, 255));
    }// GEN-LAST:event_settingsBtnMouseEntered

    private void settingsBtnMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_settingsBtnMouseExited
        // TODO add your handling code here:
        settingsBtn.setBackground(new Color(0, 0, 0));
        settingsBtn.setForeground(new Color(255, 255, 255));
        settingsBack.setBackground(new Color(0, 0, 0));
    }// GEN-LAST:event_settingsBtnMouseExited

    private void helpBtnMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_helpBtnMouseEntered
        // TODO add your handling code here:
        helpBtn.setBackground(new Color(255, 255, 255));
        helpBtn.setForeground(new Color(0, 0, 0));
        helpBack.setBackground(new Color(255, 255, 255));
    }// GEN-LAST:event_helpBtnMouseEntered

    private void helpBtnMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_helpBtnMouseExited
        // TODO add your handling code here:
        helpBtn.setBackground(new Color(0, 0, 0));
        helpBtn.setForeground(new Color(255, 255, 255));
        helpBack.setBackground(new Color(0, 0, 0));
    }// GEN-LAST:event_helpBtnMouseExited

    private void creditsBtnMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_creditsBtnMouseEntered
        // TODO add your handling code here:
        creditsBtn.setBackground(new Color(255, 255, 255));
        creditsBtn.setForeground(new Color(0, 0, 0));
        creditsBack.setBackground(new Color(255, 255, 255));
    }// GEN-LAST:event_creditsBtnMouseEntered

    private void creditsBtnMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_creditsBtnMouseExited
        // TODO add your handling code here:
        creditsBtn.setBackground(new Color(0, 0, 0));
        creditsBtn.setForeground(new Color(255, 255, 255));
        creditsBack.setBackground(new Color(0, 0, 0));
    }// GEN-LAST:event_creditsBtnMouseExited

    public void close(){
            WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        }
    private void startBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_startBtnMouseClicked
        // TODO add your handling code here:
        close();
        new Start().setVisible(true);

    }// GEN-LAST:event_startBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pageOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pageOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxA;
    private javax.swing.JPanel creditsBack;
    private javax.swing.JLabel creditsBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel helpBack;
    private javax.swing.JLabel helpBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private java.awt.Panel panel1;
    private javax.swing.JPanel settingsBack;
    private javax.swing.JLabel settingsBtn;
    private javax.swing.JPanel startBack;
    private javax.swing.JLabel startBtn;
    // End of variables declaration//GEN-END:variables
}
