/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ttt;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author WEBACC
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox1 = new java.awt.Checkbox();
        startPanel = new java.awt.Panel();
        heading = new javax.swing.JLabel();
        boxA = new javax.swing.JPanel();
        pvcBack = new javax.swing.JPanel();
        pvcBtn = new javax.swing.JLabel();
        pvpBack = new javax.swing.JPanel();
        pvpBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        menuBG = new javax.swing.JPanel();
        menuBtn = new javax.swing.JLabel();
        backBG = new javax.swing.JPanel();
        backBtn = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 700));
        setSize(new java.awt.Dimension(550, 700));

        startPanel.setBackground(new java.awt.Color(0, 0, 0));
        startPanel.setForeground(new java.awt.Color(255, 255, 255));
        startPanel.setPreferredSize(new java.awt.Dimension(333, 555));

        heading.setBackground(new java.awt.Color(0, 0, 0));
        heading.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("TIC TAC TOE");

        boxA.setBackground(new java.awt.Color(0, 0, 0));
        boxA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        boxA.setForeground(new java.awt.Color(255, 255, 255));
        boxA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        boxA.setPreferredSize(new java.awt.Dimension(321, 65));
        boxA.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        pvcBack.setBackground(new java.awt.Color(0, 0, 0));
        pvcBack.setForeground(new java.awt.Color(255, 255, 255));

        pvcBtn.setBackground(new java.awt.Color(0, 0, 0));
        pvcBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pvcBtn.setForeground(new java.awt.Color(255, 255, 255));
        pvcBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pvcBtn.setText("Player Vs Computer");
        pvcBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pvcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pvcBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvcBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvcBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pvcBackLayout = new javax.swing.GroupLayout(pvcBack);
        pvcBack.setLayout(pvcBackLayout);
        pvcBackLayout.setHorizontalGroup(
            pvcBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pvcBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );
        pvcBackLayout.setVerticalGroup(
            pvcBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pvcBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        boxA.add(pvcBack);

        pvpBack.setBackground(new java.awt.Color(0, 0, 0));
        pvpBack.setForeground(new java.awt.Color(255, 255, 255));

        pvpBtn.setBackground(new java.awt.Color(0, 0, 0));
        pvpBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pvpBtn.setForeground(new java.awt.Color(255, 255, 255));
        pvpBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pvpBtn.setText("Player Vs Player");
        pvpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pvpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pvpBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pvpBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pvpBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pvpBackLayout = new javax.swing.GroupLayout(pvpBack);
        pvpBack.setLayout(pvpBackLayout);
        pvpBackLayout.setHorizontalGroup(
            pvpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pvpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );
        pvpBackLayout.setVerticalGroup(
            pvpBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pvpBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );

        boxA.add(pvpBack);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        menuBG.setBackground(new java.awt.Color(0, 0, 0));
        menuBG.setForeground(new java.awt.Color(255, 255, 255));

        menuBtn.setBackground(new java.awt.Color(0, 0, 0));
        menuBtn.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        menuBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuBtn.setText("=");
        menuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuBGLayout = new javax.swing.GroupLayout(menuBG);
        menuBG.setLayout(menuBGLayout);
        menuBGLayout.setHorizontalGroup(
            menuBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        menuBGLayout.setVerticalGroup(
            menuBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        backBG.setBackground(new java.awt.Color(0, 0, 0));
        backBG.setForeground(new java.awt.Color(255, 255, 255));

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtn.setText("<-");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backBGLayout = new javax.swing.GroupLayout(backBG);
        backBG.setLayout(backBGLayout);
        backBGLayout.setHorizontalGroup(
            backBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        backBGLayout.setVerticalGroup(
            backBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(backBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(backBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boxA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 63, Short.MAX_VALUE)
                .addComponent(boxA, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(280, 280, 280))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        // TODO add your handling code here:
        backBtn.setBackground(new Color(255,255,255));
        backBtn.setForeground(new Color(0,0,0));
        backBG.setBackground(new Color(255,255,255));
        
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        // TODO add your handling code here:
        backBtn.setBackground(new Color(0,0,0));
        backBtn.setForeground(new Color(255,255,255));
        backBG.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_backBtnMouseExited

    private void menuBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMouseEntered
        // TODO add your handling code here:
        menuBtn.setBackground(new Color(255,255,255));
        menuBtn.setForeground(new Color(0,0,0));
        menuBG.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_menuBtnMouseEntered

    private void menuBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMouseExited
        // TODO add your handling code here:
        menuBtn.setBackground(new Color(0,0,0));
        menuBtn.setForeground(new Color(255,255,255));
        menuBG.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_menuBtnMouseExited

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        close();
        new pageOne().setVisible(true);
    }//GEN-LAST:event_backBtnMouseClicked

    private void menuBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBtnMouseClicked
        // TODO add your handling code here:
        close();
        new pageOne().setVisible(true);
    }//GEN-LAST:event_menuBtnMouseClicked

    private void pvcBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvcBtnMouseEntered
        // TODO add your handling code here:
        pvcBtn.setBackground(new Color(255,255,255));
        pvcBtn.setForeground(new Color(0,0,0));
        pvcBack.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_pvcBtnMouseEntered

    private void pvcBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvcBtnMouseExited
        // TODO add your handling code here:
        pvcBtn.setBackground(new Color(0,0,0));
        pvcBtn.setForeground(new Color(255,255,255));
        pvcBack.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_pvcBtnMouseExited

    private void pvpBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvpBtnMouseEntered
        // TODO add your handling code here:
        pvpBtn.setBackground(new Color(255,255,255));
        pvpBtn.setForeground(new Color(0,0,0));
        pvpBack.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_pvpBtnMouseEntered

    private void pvpBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvpBtnMouseExited
        // TODO add your handling code here:
        pvpBtn.setBackground(new Color(0,0,0));
        pvpBtn.setForeground(new Color(255,255,255));
        pvpBack.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_pvpBtnMouseExited

    public void close(){
            WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    private void pvcBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvcBtnMouseClicked
        // TODO add your handling code here:
        close();
        new pvc().setVisible(true);
        
    }//GEN-LAST:event_pvcBtnMouseClicked

    private void pvpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pvpBtnMouseClicked
        // TODO add your handling code here:
        close();
        new pvp().setVisible(true);
    }//GEN-LAST:event_pvpBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backBG;
    private javax.swing.JLabel backBtn;
    private javax.swing.JPanel boxA;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel heading;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menuBG;
    private javax.swing.JLabel menuBtn;
    private javax.swing.JPanel pvcBack;
    private javax.swing.JLabel pvcBtn;
    private javax.swing.JPanel pvpBack;
    private javax.swing.JLabel pvpBtn;
    private java.awt.Panel startPanel;
    // End of variables declaration//GEN-END:variables
}
